title: Docker Registry User Interface
description: The simplest and most complete UI for your private registry!
url: https://joxit.dev/docker-registry-ui
google_analytics: G-T158HYBVZ2
remote_theme: joxit/joxit.github.io
author: Jones Magloire
twitter:
  username: Joxit
instagram:
  username: jox.it
defaults:
  - scope:
      path: ""
    values:
      image: /screenshot.png
plugins:
  - jekyll-seo-tag